language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ur13lfr14s/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ur13lfr14s/react-test npm test

after_success:
  - docker build -t ur13lfr14s/multi-client ./client
  - docker build -t ur13lfr14s/multi-nginx ./nginx
  - docker build -t ur13lfr14s/multi-server ./server
  - docker build -t ur13lfr14s/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push ur13lfr14s/multi-client
  - docker push ur13lfr14s/multi-nginx 
  - docker push ur13lfr14s/multi-server
  - docker push ur13lfr14s/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: lasticbeanstalk-us-east-2-986633311192
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY